window.NEOMANMOLLA_DATA = {
  settings: {
    languages: [
      { id: "ko", label: "한국어" },
      { id: "ja", label: "日本語" },
    ],
    playerCounts: [4, 5, 6],
    defaultPlayerLangs: ["ko", "ja", "ko", "ja", "ko", "ja"],
    profileCategories: ["hair", "outfit", "item", "aura"],
    profileTabs: ["parts", "artist", "frame"],
    mainMenu: ["solo-start", "room-create", "profile", "guide", "packs", "news"],
    audiencePresets: [
      { id: "off", label: "관전 없음", size: 0, swing: 0 },
      { id: "small", label: "친구 20명", size: 20, swing: 0.58 },
      { id: "stream", label: "방송 100명", size: 100, swing: 0.64 },
      { id: "fandom", label: "팬덤 300명", size: 300, swing: 0.7 },
    ],
  },
  playerNames: ["민서", "도윤", "지우", "하준", "서연", "유나"],
  avatars: [
    { label: "ME", src: "./assets/ui/avatar-front-blue.png" },
    { label: "DO", src: "./assets/ui/avatar-front-red.png" },
    { label: "JI", src: "./assets/ui/avatar-front-purple.png" },
    { label: "HA", src: "./assets/ui/avatar-front-green.png" },
    { label: "SE", src: "./assets/ui/avatar-front-yellow.png" },
    { label: "YU", src: "./assets/ui/avatar-front-teal.png" },
  ],
  frames: [
    { id: "lime", label: "라임" },
    { id: "coral", label: "코랄" },
    { id: "gold", label: "골드" },
    { id: "stage", label: "무대" },
    { id: "holo", label: "홀로" },
    { id: "heart", label: "하트" },
  ],
  biasStyles: [
    { id: "main-vocal", label: "메보", detail: "맑은 보컬, 하트 마이크" },
    { id: "main-dancer", label: "메댄", detail: "댄스 브레이크, 실버 체인" },
    { id: "center", label: "센터", detail: "엔딩요정, 별빛 글리터" },
    { id: "rapper", label: "래퍼", detail: "강한 랩톤, 블랙 캡" },
  ],
  dressUp: {
    hair: [
      { id: "short", label: "쇼트컷", color: "#6aa7ff" },
      { id: "wave", label: "웨이브", color: "#ff4d6d" },
      { id: "silver", label: "실버", color: "#d8e5ff" },
      { id: "black", label: "블랙", color: "#16181d" },
      { id: "mint-twin", label: "민트 트윈", color: "#4de0bd" },
      { id: "pink-bang", label: "핑크 앞머리", color: "#ff8fb3" },
      { id: "gold-tail", label: "골드 포니", color: "#ffd166" },
      { id: "violet", label: "바이올렛", color: "#9b7bff" },
    ],
    outfit: [
      { id: "stage-black", label: "블랙 무대복", color: "#20232b" },
      { id: "school", label: "스쿨룩", color: "#6aa7ff" },
      { id: "pink", label: "핑크 코디", color: "#ff8fb3" },
      { id: "street", label: "스트릿", color: "#b8f35f" },
      { id: "varsity", label: "바시티 재킷", color: "#4de0bd" },
      { id: "royal", label: "로열 무대복", color: "#ffd166" },
      { id: "denim", label: "데님 세트", color: "#6aa7ff" },
      { id: "techwear", label: "테크웨어", color: "#9b7bff" },
    ],
    item: [
      { id: "lightstick", label: "응원봉", symbol: "✦" },
      { id: "mic", label: "마이크", symbol: "♪" },
      { id: "photocard", label: "포카", symbol: "▣" },
      { id: "crown", label: "왕관", symbol: "♛" },
      { id: "camera", label: "직캠 카메라", symbol: "◎" },
      { id: "heart-glasses", label: "하트 안경", symbol: "♡" },
      { id: "star-bag", label: "별 가방", symbol: "☆" },
      { id: "cat-ear", label: "고양이 귀", symbol: "⌃" },
    ],
    aura: [
      { id: "sparkle", label: "스파클", color: "#ffd166" },
      { id: "neon", label: "네온", color: "#4de0bd" },
      { id: "heart", label: "하트", color: "#ff4d6d" },
      { id: "star", label: "별빛", color: "#6aa7ff" },
      { id: "spotlight", label: "스포트라이트", color: "#f7f3ea" },
      { id: "purple", label: "퍼플 글로우", color: "#9b7bff" },
    ],
  },
  idolGroups: [
    { id: "v01d", type: "band", name: "v01d", tags: ["공식 등록", "5인조 밴드", "자사 아티스트"], owned: true, status: "registered" },
    { id: "bts", type: "boy", name: "BTS", tags: ["레전드", "퍼포먼스", "글로벌"] },
    { id: "seventeen", type: "boy", name: "SEVENTEEN", tags: ["자체제작", "칼군무", "예능감"] },
    { id: "stray-kids", type: "boy", name: "Stray Kids", tags: ["강한 사운드", "퍼포먼스", "글로벌"] },
    { id: "enhypen", type: "boy", name: "ENHYPEN", tags: ["서사", "퍼포먼스", "팬덤"] },
    { id: "txt", type: "boy", name: "TXT", tags: ["청량", "콘셉트", "스토리"] },
    { id: "blackpink", type: "girl", name: "BLACKPINK", tags: ["아이콘", "패션", "글로벌"] },
    { id: "twice", type: "girl", name: "TWICE", tags: ["히트곡", "팬서비스", "콘서트"] },
    { id: "aespa", type: "girl", name: "aespa", tags: ["세계관", "보컬", "콘셉트"] },
    { id: "ive", type: "girl", name: "IVE", tags: ["자기확신", "비주얼", "후렴"] },
    { id: "le-sserafim", type: "girl", name: "LE SSERAFIM", tags: ["퍼포먼스", "당당함", "무대"] },
  ],
  themes: [
    { id: "neon-basement", label: "네온 지하실", vibe: "어두운 조명과 형광 사인", accent: "#4de0bd" },
    { id: "after-class", label: "교실 after", vibe: "방과 후 책상 사이에서 하는 몰래 게임", accent: "#ffd166" },
    { id: "space-station", label: "우주 정거장", vibe: "둥둥 뜨는 회의실과 차가운 조명", accent: "#6aa7ff" },
    { id: "retro-gym", label: "레트로 체육관", vibe: "응원봉과 확성기가 있는 체육대회", accent: "#ff4d6d" },
    { id: "idol-backstage", label: "아이돌 백스테이지", vibe: "대기실, 포토월, 무대 전 긴장감", accent: "#9b7bff" },
  ],
  notices: [
    {
      id: "v01d-registered",
      type: "artist",
      groupId: "v01d",
      date: "2026-05-01",
      title: "v01d 등록 완료",
      body: "남자 5인조 밴드그룹 v01d가 공식 등록되었습니다.",
    },
    {
      id: "kpop-pack-open",
      type: "pack",
      packId: "kpop",
      date: "2026-05-01",
      title: "케이팝 팬덤 질문팩 추가",
      body: "최애, 컴백, 콘서트, 포카 주제로 플레이할 수 있습니다.",
    },
  ],
  packs: [
    {
      id: "kpop",
      name: "케이팝 팬덤",
      count: 52,
      status: "팬덤",
      tone: "최애 얘기만으로 바로 싸움 나는 질문",
      rounds: [
        {
          title: "컴백",
          innocent: "컴백 첫날 팬들이 제일 먼저 확인하는 건?",
          fake: "컴백 한참 뒤에 봐도 되는 건?",
          answers: ["뮤비", "음원 순위", "직캠", "포카 시세", "비하인드", "스케줄표"],
          botAnswers: ["뮤비", "음원 순위", "직캠", "응원법", "쇼케이스"],
          fakeAnswers: ["비하인드", "스케줄표", "자막 인터뷰", "굿즈 재고"],
        },
        {
          title: "최애",
          innocent: "최애 입덕 포인트로 강한 건?",
          fake: "최애 탈덕 방어에 필요한 건?",
          answers: ["무대 표정", "라이브", "팬사랑", "예능감", "소통", "실물 후기"],
          botAnswers: ["무대 표정", "라이브", "팬사랑", "예능감"],
          fakeAnswers: ["소통", "실물 후기", "꾸준한 활동", "좋은 스타일링"],
        },
        {
          title: "콘서트",
          innocent: "콘서트 가기 전에 꼭 챙길 건?",
          fake: "콘서트 끝나고 챙기면 되는 건?",
          answers: ["티켓", "응원봉", "보조배터리", "슬로건", "후기", "굿즈 정리"],
          botAnswers: ["티켓", "응원봉", "보조배터리", "슬로건"],
          fakeAnswers: ["후기", "굿즈 정리", "사진 백업", "셋리스트 복습"],
        },
        {
          title: "포카",
          innocent: "포카 교환할 때 제일 중요한 건?",
          fake: "포카 보관할 때 제일 중요한 건?",
          answers: ["하자 확인", "시세", "인증샷", "직거래 장소", "슬리브", "탑로더"],
          botAnswers: ["하자 확인", "시세", "인증샷", "직거래 장소"],
          fakeAnswers: ["슬리브", "탑로더", "습기 방지", "바인더"],
        },
      ],
    },
    {
      id: "daily",
      name: "일상",
      count: 48,
      status: "기본",
      tone: "처음 하는 친구도 바로 답하는 질문",
      rounds: [
        {
          title: "편의점",
          innocent: "편의점에서 자주 사는 야식은?",
          fake: "편의점에서 굳이 안 사는 음식은?",
          answers: ["삼각김밥", "컵라면", "핫바", "제로콜라", "생수", "초코우유"],
          botAnswers: ["삼각김밥", "컵라면", "핫바", "도시락", "떡볶이"],
          fakeAnswers: ["생수", "껌", "샐러드", "견과류"],
        },
        {
          title: "배달",
          innocent: "여럿이 시키기 좋은 배달 메뉴는?",
          fake: "혼자 시키기 좋은 배달 메뉴는?",
          answers: ["치킨", "피자", "마라탕", "떡볶이", "초밥", "햄버거"],
          botAnswers: ["치킨", "피자", "마라탕", "떡볶이", "족발"],
          fakeAnswers: ["햄버거", "초밥", "샐러드", "덮밥"],
        },
        {
          title: "주말",
          innocent: "친구들이랑 주말에 하기 좋은 건?",
          fake: "혼자 주말에 하기 좋은 건?",
          answers: ["방탈출", "맛집", "보드게임", "노래방", "영화", "낮잠"],
          botAnswers: ["방탈출", "맛집", "보드게임", "노래방", "카페"],
          fakeAnswers: ["낮잠", "넷플릭스", "산책", "게임"],
        },
        {
          title: "단톡",
          innocent: "단톡방에서 반응 좋은 말투는?",
          fake: "단톡방에서 분위기 식는 말투는?",
          answers: ["짧고 웃기게", "리액션 크게", "짤 보내기", "바로 답장", "읽씹", "팩폭"],
          botAnswers: ["짧고 웃기게", "리액션 크게", "짤 보내기", "바로 답장"],
          fakeAnswers: ["읽씹", "팩폭", "장문 훈수", "갑분진지"],
        },
      ],
    },
    {
      id: "romance",
      name: "연애/썸",
      count: 36,
      status: "인기",
      tone: "대답만 봐도 놀림거리가 생기는 질문",
      rounds: [
        {
          title: "첫 데이트",
          innocent: "첫 데이트 장소로 좋은 곳은?",
          fake: "혼자 시간 보내기 좋은 곳은?",
          answers: ["영화관", "카페", "한강", "전시회", "PC방", "집"],
          botAnswers: ["영화관", "카페", "한강", "전시회", "맛집"],
          fakeAnswers: ["집", "PC방", "서점", "산책"],
        },
        {
          title: "답장",
          innocent: "호감 있을 때 보내기 좋은 답장은?",
          fake: "관심 없을 때 보내기 쉬운 답장은?",
          answers: ["ㅋㅋㅋㅋ", "언제 볼래?", "나도 좋아", "사진 보내기", "응", "바쁨"],
          botAnswers: ["ㅋㅋㅋㅋ", "언제 볼래?", "나도 좋아", "사진 보내기"],
          fakeAnswers: ["응", "바쁨", "나중에", "읽고 답 없음"],
        },
        {
          title: "선물",
          innocent: "가볍게 받으면 기분 좋은 선물은?",
          fake: "받으면 조금 부담스러운 선물은?",
          answers: ["커피 쿠폰", "디저트", "향수", "꽃", "커플템", "손편지"],
          botAnswers: ["커피 쿠폰", "디저트", "꽃", "키링"],
          fakeAnswers: ["커플템", "비싼 향수", "손편지", "옷"],
        },
      ],
    },
    {
      id: "party",
      name: "MT/술자리",
      count: 42,
      status: "파티",
      tone: "짧고 웃긴 단체용 질문",
      rounds: [
        {
          title: "여행",
          innocent: "친구들이랑 여행 가면 꼭 하는 일은?",
          fake: "혼자 여행 가면 꼭 하는 일은?",
          answers: ["맛집 찾기", "사진 찍기", "숙소에서 쉬기", "야시장", "카페 투어", "늦잠"],
          botAnswers: ["맛집 찾기", "사진 찍기", "야시장", "카페 투어", "기념품 쇼핑"],
          fakeAnswers: ["늦잠", "혼밥", "숙소에서 쉬기", "책 읽기"],
        },
        {
          title: "노래방",
          innocent: "노래방 첫 곡으로 괜찮은 노래 스타일은?",
          fake: "노래방 마지막 곡으로 괜찮은 노래 스타일은?",
          answers: ["발라드", "댄스곡", "아이돌곡", "랩", "OST", "떼창곡"],
          botAnswers: ["댄스곡", "아이돌곡", "신나는 곡", "떼창곡", "아는 노래"],
          fakeAnswers: ["발라드", "이별 노래", "고음곡", "잔잔한 OST"],
        },
        {
          title: "술게임",
          innocent: "처음 만난 사람들과 하기 쉬운 술게임은?",
          fake: "친한 사람끼리 해야 덜 민망한 술게임은?",
          answers: ["369", "눈치게임", "딸기게임", "훈민정음", "진실게임", "이미지게임"],
          botAnswers: ["369", "눈치게임", "딸기게임", "훈민정음"],
          fakeAnswers: ["진실게임", "이미지게임", "밸런스게임", "왕게임"],
        },
        {
          title: "숙소",
          innocent: "MT 숙소에서 제일 먼저 정할 건?",
          fake: "MT 숙소에서 마지막에 정해도 되는 건?",
          answers: ["방 배정", "장보기", "저녁 메뉴", "술 담당", "아침 메뉴", "청소 순서"],
          botAnswers: ["방 배정", "장보기", "저녁 메뉴", "술 담당"],
          fakeAnswers: ["아침 메뉴", "청소 순서", "귀가 시간", "사진 정리"],
        },
      ],
    },
  ],
  locales: {
    ja: {
      playerNames: ["ミンソ", "ドユン", "ジウ", "ハジュン", "ソヨン", "ユナ"],
      frames: {
        lime: "ライム",
        coral: "コーラル",
        gold: "ゴールド",
        stage: "ステージ",
        holo: "ホログラム",
        heart: "ハート",
      },
      biasStyles: {
        "main-vocal": { label: "メボ", detail: "澄んだボーカル、ハートマイク" },
        "main-dancer": { label: "メインダンサー", detail: "ダンスブレイク、シルバーチェーン" },
        center: { label: "センター", detail: "エンディング妖精、星グリッター" },
        rapper: { label: "ラッパー", detail: "強めのラップ、ブラックキャップ" },
      },
      dressUp: {
        hair: {
          short: "ショート",
          wave: "ウェーブ",
          silver: "シルバー",
          black: "ブラック",
          "mint-twin": "ミントツイン",
          "pink-bang": "ピンク前髪",
          "gold-tail": "ゴールドポニー",
          violet: "バイオレット",
        },
        outfit: {
          "stage-black": "黒ステージ衣装",
          school: "スクールルック",
          pink: "ピンクコーデ",
          street: "ストリート",
          varsity: "バーシティジャケット",
          royal: "ロイヤル衣装",
          denim: "デニムセット",
          techwear: "テックウェア",
        },
        item: {
          lightstick: "ペンライト",
          mic: "マイク",
          photocard: "トレカ",
          crown: "王冠",
          camera: "チッケムカメラ",
          "heart-glasses": "ハート眼鏡",
          "star-bag": "星バッグ",
          "cat-ear": "猫耳",
        },
        aura: {
          sparkle: "スパークル",
          neon: "ネオン",
          heart: "ハート",
          star: "星明かり",
          spotlight: "スポットライト",
          purple: "パープルグロー",
        },
      },
      idolGroups: {
        v01d: { tags: ["公式登録", "5人組バンド", "自社アーティスト"], status: "登録済み" },
        bts: { tags: ["レジェンド", "パフォーマンス", "グローバル"] },
        seventeen: { tags: ["自主制作", "シンクロダンス", "バラエティ"] },
        "stray-kids": { tags: ["強いサウンド", "パフォーマンス", "グローバル"] },
        enhypen: { tags: ["物語", "パフォーマンス", "ファンダム"] },
        txt: { tags: ["爽やか", "コンセプト", "ストーリー"] },
        blackpink: { tags: ["アイコン", "ファッション", "グローバル"] },
        twice: { tags: ["ヒット曲", "ファンサ", "コンサート"] },
        aespa: { tags: ["世界観", "ボーカル", "コンセプト"] },
        ive: { tags: ["自己肯定感", "ビジュアル", "サビ"] },
        "le-sserafim": { tags: ["パフォーマンス", "堂々", "ステージ"] },
      },
      themes: {
        "neon-basement": { label: "ネオン地下室", vibe: "暗い照明と蛍光サイン" },
        "after-class": { label: "放課後の教室", vibe: "机の間でこっそり遊ぶ放課後" },
        "space-station": { label: "宇宙ステーション", vibe: "浮遊する会議室と冷たい照明" },
        "retro-gym": { label: "レトロ体育館", vibe: "ペンライトと拡声器のある体育祭" },
        "idol-backstage": { label: "アイドル楽屋", vibe: "控室、フォトウォール、本番前の緊張感" },
      },
      audiencePresets: {
        off: "観戦なし",
        small: "友だち20人",
        stream: "配信100人",
        fandom: "ファンダム300人",
      },
      notices: {
        "v01d-registered": {
          title: "v01d 登録完了",
          body: "男性5人組バンドグループ v01d が公式登録されました。",
        },
        "kpop-pack-open": {
          title: "K-POPファンダム質問パック追加",
          body: "推し、カムバック、コンサート、トレカのテーマで遊べます。",
        },
      },
      packs: {
        kpop: {
          name: "K-POPファンダム",
          status: "ファン",
          tone: "推しの話だけで盛り上がれる質問",
          rounds: [
            {
              title: "カムバック",
              innocent: "カムバ初日にファンがまず確認するものは？",
              fake: "カムバ後しばらくしてから見てもいいものは？",
              answers: ["MV", "音源順位", "チッケム", "トレカ相場", "ビハインド", "スケジュール"],
              botAnswers: ["MV", "音源順位", "チッケム", "掛け声", "ショーケース"],
              fakeAnswers: ["ビハインド", "スケジュール", "字幕インタビュー", "グッズ在庫"],
            },
            {
              title: "推し",
              innocent: "推しにハマる入口として強いものは？",
              fake: "推し続けるために必要なものは？",
              answers: ["ステージ表情", "ライブ", "ファン愛", "バラエティ力", "交流", "実物レポ"],
              botAnswers: ["ステージ表情", "ライブ", "ファン愛", "バラエティ力"],
              fakeAnswers: ["交流", "実物レポ", "継続活動", "良いスタイリング"],
            },
            {
              title: "コンサート",
              innocent: "コンサート前に必ず持っていくものは？",
              fake: "コンサート後に整理すればいいものは？",
              answers: ["チケット", "ペンライト", "モバイルバッテリー", "スローガン", "感想", "グッズ整理"],
              botAnswers: ["チケット", "ペンライト", "モバイルバッテリー", "スローガン"],
              fakeAnswers: ["感想", "グッズ整理", "写真バックアップ", "セトリ復習"],
            },
            {
              title: "トレカ",
              innocent: "トレカ交換で一番大事なことは？",
              fake: "トレカ保管で一番大事なことは？",
              answers: ["傷確認", "相場", "認証写真", "手渡し場所", "スリーブ", "トップローダー"],
              botAnswers: ["傷確認", "相場", "認証写真", "手渡し場所"],
              fakeAnswers: ["スリーブ", "トップローダー", "湿気対策", "バインダー"],
            },
          ],
        },
        daily: {
          name: "日常",
          status: "基本",
          tone: "初めてでもすぐ答えられる質問",
          rounds: [
            {
              title: "コンビニ",
              innocent: "コンビニでよく買う夜食は？",
              fake: "コンビニであえて買わない食べ物は？",
              answers: ["おにぎり", "カップ麺", "ホットスナック", "ゼロコーラ", "水", "チョコ牛乳"],
              botAnswers: ["おにぎり", "カップ麺", "ホットスナック", "弁当", "トッポッキ"],
              fakeAnswers: ["水", "ガム", "サラダ", "ナッツ"],
            },
            {
              title: "デリバリー",
              innocent: "みんなで頼むのに良いデリバリーは？",
              fake: "一人で頼むのに良いデリバリーは？",
              answers: ["チキン", "ピザ", "麻辣湯", "トッポッキ", "寿司", "ハンバーガー"],
              botAnswers: ["チキン", "ピザ", "麻辣湯", "トッポッキ", "ポッサム"],
              fakeAnswers: ["ハンバーガー", "寿司", "サラダ", "丼"],
            },
            {
              title: "週末",
              innocent: "友だちと週末にやると楽しいことは？",
              fake: "一人の週末にやると楽しいことは？",
              answers: ["脱出ゲーム", "グルメ", "ボードゲーム", "カラオケ", "映画", "昼寝"],
              botAnswers: ["脱出ゲーム", "グルメ", "ボードゲーム", "カラオケ", "カフェ"],
              fakeAnswers: ["昼寝", "Netflix", "散歩", "ゲーム"],
            },
            {
              title: "グループチャット",
              innocent: "グループチャットで盛り上がる返し方は？",
              fake: "グループチャットで空気が冷える返し方は？",
              answers: ["短く面白く", "大きめリアクション", "画像を送る", "すぐ返信", "既読スルー", "正論パンチ"],
              botAnswers: ["短く面白く", "大きめリアクション", "画像を送る", "すぐ返信"],
              fakeAnswers: ["既読スルー", "正論パンチ", "長文アドバイス", "急に真面目"],
            },
          ],
        },
        romance: {
          name: "恋愛/気になる人",
          status: "人気",
          tone: "答えだけでいじれる質問",
          rounds: [
            {
              title: "初デート",
              innocent: "初デートに良い場所は？",
              fake: "一人時間に良い場所は？",
              answers: ["映画館", "カフェ", "川沿い", "展示会", "ネットカフェ", "家"],
              botAnswers: ["映画館", "カフェ", "川沿い", "展示会", "レストラン"],
              fakeAnswers: ["家", "ネットカフェ", "本屋", "散歩"],
            },
            {
              title: "返信",
              innocent: "好意がある時に送りやすい返信は？",
              fake: "興味が薄い時に送りがちな返信は？",
              answers: ["笑笑笑", "いつ会う？", "私も好き", "写真を送る", "うん", "忙しい"],
              botAnswers: ["笑笑笑", "いつ会う？", "私も好き", "写真を送る"],
              fakeAnswers: ["うん", "忙しい", "また今度", "既読で止める"],
            },
            {
              title: "プレゼント",
              innocent: "軽くもらって嬉しいプレゼントは？",
              fake: "もらうと少し重いプレゼントは？",
              answers: ["コーヒー券", "デザート", "香水", "花", "ペアグッズ", "手紙"],
              botAnswers: ["コーヒー券", "デザート", "花", "キーホルダー"],
              fakeAnswers: ["ペアグッズ", "高い香水", "手紙", "服"],
            },
          ],
        },
        party: {
          name: "合宿/飲み会",
          status: "パーティー",
          tone: "短く笑えるグループ向け質問",
          rounds: [
            {
              title: "旅行",
              innocent: "友だちと旅行に行ったら必ずすることは？",
              fake: "一人旅に行ったら必ずすることは？",
              answers: ["グルメ探し", "写真を撮る", "宿で休む", "夜市", "カフェ巡り", "寝坊"],
              botAnswers: ["グルメ探し", "写真を撮る", "夜市", "カフェ巡り", "お土産探し"],
              fakeAnswers: ["寝坊", "一人ご飯", "宿で休む", "読書"],
            },
            {
              title: "カラオケ",
              innocent: "カラオケの最初の曲に良いジャンルは？",
              fake: "カラオケの最後の曲に良いジャンルは？",
              answers: ["バラード", "ダンス曲", "アイドル曲", "ラップ", "OST", "みんなで歌う曲"],
              botAnswers: ["ダンス曲", "アイドル曲", "盛り上がる曲", "みんなで歌う曲", "知ってる曲"],
              fakeAnswers: ["バラード", "失恋ソング", "高音曲", "静かなOST"],
            },
            {
              title: "飲みゲーム",
              innocent: "初対面でもやりやすい飲みゲームは？",
              fake: "仲良い人同士じゃないと気まずい飲みゲームは？",
              answers: ["369", "タイミングゲーム", "いちごゲーム", "しりとり", "真実ゲーム", "イメージゲーム"],
              botAnswers: ["369", "タイミングゲーム", "いちごゲーム", "しりとり"],
              fakeAnswers: ["真実ゲーム", "イメージゲーム", "究極の選択", "王様ゲーム"],
            },
            {
              title: "宿",
              innocent: "合宿の宿で最初に決めることは？",
              fake: "合宿の宿で最後に決めてもいいことは？",
              answers: ["部屋割り", "買い出し", "夕飯", "お酒係", "朝ごはん", "掃除順"],
              botAnswers: ["部屋割り", "買い出し", "夕飯", "お酒係"],
              fakeAnswers: ["朝ごはん", "掃除順", "帰る時間", "写真整理"],
            },
          ],
        },
      },
    },
  },
};
