window.NEOMANMOLLA_DATA = {
  settings: {
    languages: [
      { id: "ko", label: "한국어" },
      { id: "ja", label: "日本語" },
    ],
    playerCounts: [4, 5, 6],
    defaultPlayerLangs: ["ko", "ja", "ko", "ja", "ko", "ja"],
    profileCategories: ["preset", "hair", "top", "pants", "shoes", "item", "back", "aura"],
    profileTabs: ["parts", "artist", "frame"],
    characterPoses: [
      { id: "idle", label: "기본" },
      { id: "point", label: "삿대질" },
      { id: "stage", label: "무대" },
      { id: "think", label: "의심" },
    ],
    mainMenu: ["quick-match", "room-create", "solo-start", "profile", "guide", "packs", "news"],
    questionThemePacks: ["kpop"],
    audiencePresets: [
      { id: "off", label: "관전 없음", size: 0, swing: 0 },
      { id: "small", label: "친구 20명", size: 20, swing: 0.58 },
      { id: "stream", label: "방송 100명", size: 100, swing: 0.64 },
      { id: "fandom", label: "팬덤 300명", size: 300, swing: 0.7 },
    ],
  },
  heroSlides: [
    {
      id: "accuse",
      image: "./assets/ui/hero-accuse-pixel-900.png",
      tag: "2분 소셜 추리",
      title: "답변 하나로 친구를 의심하세요.",
      body: "한 명만 다른 질문을 받습니다. 자연스러운 척하는 답변을 찾아내세요.",
    },
    {
      id: "v01d",
      image: "./assets/ui/hero-v01d-accuse-pixel-900.png",
      tag: "V01D 질문 테마",
      title: "최애 밴드 테마로 바로 시작하세요.",
      body: "V01D를 질문 테마로 고르고 팬덤끼리 서로의 답변을 의심해보세요.",
    },
  ],
  characterSets: [
    { id: "band", label: "밴드 캐릭터", sheet: "./assets/ui/v01d-sprite-sheet.png", columns: 5, rows: 4, aspect: "4 / 5" },
    { id: "v01d", label: "V01D 캐릭터", groupId: "v01d", sheet: "./assets/ui/v01d-official-sprite-sheet.png", columns: 5, rows: 4, aspect: "6 / 5" },
  ],
  playerNames: ["민서", "도윤", "지우", "하준", "서연", "유나"],
  avatars: [
    { label: "ME", src: "./assets/ui/avatar-front-blue.png" },
    { label: "DO", src: "./assets/ui/avatar-front-red.png" },
    { label: "JI", src: "./assets/ui/avatar-front-purple.png" },
    { label: "HA", src: "./assets/ui/avatar-front-green.png" },
    { label: "SE", src: "./assets/ui/avatar-front-yellow.png" },
    { label: "YU", src: "./assets/ui/avatar-front-teal.png" },
  ],
  frames: [
    { id: "lime", label: "라임" },
    { id: "coral", label: "코랄" },
    { id: "gold", label: "골드" },
    { id: "stage", label: "무대" },
    { id: "holo", label: "홀로" },
    { id: "heart", label: "하트" },
  ],
  biasStyles: [
    { id: "main-vocal", label: "메보", detail: "맑은 보컬, 하트 마이크" },
    { id: "main-dancer", label: "메댄", detail: "댄스 브레이크, 실버 체인" },
    { id: "center", label: "센터", detail: "엔딩요정, 별빛 글리터" },
    { id: "rapper", label: "래퍼", detail: "강한 랩톤, 블랙 캡" },
  ],
  dressUp: {
    preset: [
      { id: "custom", label: "직접 꾸미기", symbol: "DIY", rarity: "N" },
      { id: "wolf-guitar", label: "블랙 기타", symbol: "01", rarity: "SR", asset: "./assets/avatar/presets/wolf-guitar.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/wolf-guitar.png?v=20260502-029-028-028-028" },
      { id: "red-drummer", label: "레드 드러머", symbol: "02", rarity: "SR", asset: "./assets/avatar/presets/red-drummer.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/red-drummer.png?v=20260502-029-028-028-028" },
      { id: "ash-keyboard", label: "애쉬 키보드", symbol: "03", rarity: "SR", asset: "./assets/avatar/presets/ash-keyboard.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/ash-keyboard.png?v=20260502-029-028-028-028" },
      { id: "blond-bass", label: "블론드 베이스", symbol: "04", rarity: "SR", asset: "./assets/avatar/presets/blond-bass.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/blond-bass.png?v=20260502-029-028-028-028" },
      { id: "pink-vocal", label: "핑크 보컬", symbol: "05", rarity: "SR", asset: "./assets/avatar/presets/pink-vocal.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/pink-vocal.png?v=20260502-029-028-028-028" },
      { id: "stripe-bass", label: "스트라이프 베이스", symbol: "06", rarity: "SR", asset: "./assets/avatar/presets/stripe-bass.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/stripe-bass.png?v=20260502-029-028-028-028" },
      { id: "silver-mic", label: "실버 마이크", symbol: "07", rarity: "SR", asset: "./assets/avatar/presets/silver-mic.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/silver-mic.png?v=20260502-029-028-028-028" },
      { id: "hime-stage", label: "히메 스테이지", symbol: "08", rarity: "SR", asset: "./assets/avatar/presets/hime-stage.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/hime-stage.png?v=20260502-029-028-028-028" },
      { id: "mint-fan", label: "민트 팬룩", symbol: "09", rarity: "SR", asset: "./assets/avatar/presets/mint-fan.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/mint-fan.png?v=20260502-029-028-028-028" },
      { id: "purple-guitar", label: "퍼플 기타", symbol: "10", rarity: "SR", asset: "./assets/avatar/presets/purple-guitar.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/purple-guitar.png?v=20260502-029-028-028-028" },
      { id: "gold-vocal", label: "골드 보컬", symbol: "11", rarity: "SSR", asset: "./assets/avatar/presets/gold-vocal.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/gold-vocal.png?v=20260502-029-028-028-028" },
      { id: "techwear", label: "테크웨어", symbol: "12", rarity: "SSR", asset: "./assets/avatar/presets/techwear.png?v=20260502-029-028-028-028", thumb: "./assets/avatar/presets/techwear.png?v=20260502-029-028-028-028" },
    ],
    body: [
      { id: "base-m", label: "남자 기본", symbol: "M", rarity: "N", skin: "#f3b27d", asset: "./assets/avatar/body-base-m.png?v=20260502-030", thumb: "./assets/avatar/thumbs/body-base-m.png?v=20260502-030" },
      { id: "base-f", label: "여자 기본", symbol: "F", rarity: "N", skin: "#f0a978", asset: "./assets/avatar/body-base-f.png?v=20260502-030", thumb: "./assets/avatar/thumbs/body-base-f.png?v=20260502-030" },
      { id: "warm", label: "웜톤", symbol: "W", rarity: "N", skin: "#d8895f", asset: "./assets/avatar/body-warm.png?v=20260502-030", thumb: "./assets/avatar/thumbs/body-warm.png?v=20260502-030" },
      { id: "cool", label: "쿨톤", symbol: "C", rarity: "R", skin: "#f6c4a0", asset: "./assets/avatar/body-cool.png?v=20260502-030", thumb: "./assets/avatar/thumbs/body-cool.png?v=20260502-030" },
      { id: "tan", label: "태닝", symbol: "T", rarity: "R", skin: "#b96f4c", asset: "./assets/avatar/body-tan.png?v=20260502-030", thumb: "./assets/avatar/thumbs/body-tan.png?v=20260502-030" },
      { id: "porcelain", label: "포슬린", symbol: "P", rarity: "SR", skin: "#ffd7bd", asset: "./assets/avatar/body-porcelain.png?v=20260502-030", thumb: "./assets/avatar/thumbs/body-porcelain.png?v=20260502-030" },
    ],
    hair: [
      { id: "short", label: "쇼트컷", symbol: "01", rarity: "N", color: "#6aa7ff", asset: "./assets/avatar/hair-short.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-short.png?v=20260502-030" },
      { id: "wolf-black", label: "블랙 울프컷", symbol: "02", rarity: "R", color: "#16181d", asset: "./assets/avatar/hair-wolf-black.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-wolf-black.png?v=20260502-030" },
      { id: "comma-brown", label: "브라운 콤마", symbol: "03", rarity: "R", color: "#4a3328", asset: "./assets/avatar/hair-comma-brown.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-comma-brown.png?v=20260502-030" },
      { id: "wine-wave", label: "와인 웨이브", symbol: "04", rarity: "SR", color: "#9d1f45", asset: "./assets/avatar/hair-wine-wave.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-wine-wave.png?v=20260502-030" },
      { id: "center-part", label: "센터파트", symbol: "05", rarity: "R", color: "#111318", asset: "./assets/avatar/hair-center-part.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-center-part.png?v=20260502-030" },
      { id: "spike-brown", label: "브라운 스파이크", symbol: "06", rarity: "SR", color: "#9b5527", asset: "./assets/avatar/hair-spike-brown.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-spike-brown.png?v=20260502-030" },
      { id: "silver", label: "실버 레이어", symbol: "07", rarity: "SR", color: "#d8e5ff", asset: "./assets/avatar/hair-silver.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-silver.png?v=20260502-030" },
      { id: "mint-twin", label: "민트 트윈", symbol: "08", rarity: "SSR", color: "#4de0bd", asset: "./assets/avatar/hair-mint-twin.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-mint-twin.png?v=20260502-030" },
      { id: "pink-bang", label: "핑크 앞머리", symbol: "09", rarity: "SSR", color: "#ff8fb3", asset: "./assets/avatar/hair-pink-bang.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-pink-bang.png?v=20260502-030" },
      { id: "gold-tail", label: "골드 포니", symbol: "10", rarity: "SR", color: "#ffd166", asset: "./assets/avatar/hair-gold-tail.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-gold-tail.png?v=20260502-030" },
      { id: "violet", label: "바이올렛 샤기", symbol: "11", rarity: "SR", color: "#9b7bff", asset: "./assets/avatar/hair-violet.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-violet.png?v=20260502-030" },
      { id: "ash-blue", label: "애쉬 블루", symbol: "12", rarity: "SSR", color: "#6aa7ff", asset: "./assets/avatar/hair-ash-blue.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-ash-blue.png?v=20260502-030" },
      { id: "hime-black", label: "히메 블랙", symbol: "13", rarity: "SR", color: "#15161a", asset: "./assets/avatar/hair-hime-black.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-hime-black.png?v=20260502-030" },
      { id: "bob-coral", label: "코랄 단발", symbol: "14", rarity: "R", color: "#ff6f7f", asset: "./assets/avatar/hair-bob-coral.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-bob-coral.png?v=20260502-030" },
      { id: "long-ash", label: "애쉬 롱", symbol: "15", rarity: "SSR", color: "#c9d6e8", asset: "./assets/avatar/hair-long-ash.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-long-ash.png?v=20260502-030" },
      { id: "two-tone", label: "투톤 브릿지", symbol: "16", rarity: "SSR", color: "#1a1d23", accent: "#ff4d6d", asset: "./assets/avatar/hair-two-tone.png?v=20260502-030", thumb: "./assets/avatar/thumbs/hair-two-tone.png?v=20260502-030" },
    ],
    eyes: [
      { id: "soft-brown", label: "브라운 눈", symbol: "BR", rarity: "N", color: "#4a2f25", asset: "./assets/avatar/eyes-soft-brown.png?v=20260502-029", thumb: "./assets/avatar/thumbs/eyes-soft-brown.png?v=20260502-029" },
      { id: "cat-black", label: "캣츠 블랙", symbol: "CB", rarity: "R", color: "#17191f", asset: "./assets/avatar/eyes-cat-black.png?v=20260502-029", thumb: "./assets/avatar/thumbs/eyes-cat-black.png?v=20260502-029" },
      { id: "ruby", label: "루비 아이", symbol: "RB", rarity: "SR", color: "#b51d2a", asset: "./assets/avatar/eyes-ruby.png?v=20260502-029", thumb: "./assets/avatar/thumbs/eyes-ruby.png?v=20260502-029" },
      { id: "aqua", label: "아쿠아 아이", symbol: "AQ", rarity: "SR", color: "#4de0bd", asset: "./assets/avatar/eyes-aqua.png?v=20260502-029", thumb: "./assets/avatar/thumbs/eyes-aqua.png?v=20260502-029" },
      { id: "violet", label: "바이올렛 아이", symbol: "VT", rarity: "SSR", color: "#9b7bff", asset: "./assets/avatar/eyes-violet.png?v=20260502-029", thumb: "./assets/avatar/thumbs/eyes-violet.png?v=20260502-029" },
      { id: "sleepy", label: "나른한 눈", symbol: "SL", rarity: "R", color: "#2f2a28", asset: "./assets/avatar/eyes-sleepy.png?v=20260502-029", thumb: "./assets/avatar/thumbs/eyes-sleepy.png?v=20260502-029" },
    ],
    lips: [
      { id: "natural", label: "내추럴", symbol: "N", rarity: "N", color: "#d86a70", asset: "./assets/avatar/lips-natural.png?v=20260502-029", thumb: "./assets/avatar/thumbs/lips-natural.png?v=20260502-029" },
      { id: "coral", label: "코랄 립", symbol: "C", rarity: "R", color: "#ff7a72", asset: "./assets/avatar/lips-coral.png?v=20260502-029", thumb: "./assets/avatar/thumbs/lips-coral.png?v=20260502-029" },
      { id: "rose", label: "로즈 립", symbol: "R", rarity: "SR", color: "#bd4662", asset: "./assets/avatar/lips-rose.png?v=20260502-029", thumb: "./assets/avatar/thumbs/lips-rose.png?v=20260502-029" },
      { id: "gloss", label: "글로시", symbol: "G", rarity: "SR", color: "#ff9ab0", asset: "./assets/avatar/lips-gloss.png?v=20260502-029", thumb: "./assets/avatar/thumbs/lips-gloss.png?v=20260502-029" },
      { id: "dark", label: "다크 레드", symbol: "D", rarity: "SSR", color: "#7c1d2d", asset: "./assets/avatar/lips-dark.png?v=20260502-029", thumb: "./assets/avatar/thumbs/lips-dark.png?v=20260502-029" },
    ],
    beauty: [
      { id: "none", label: "없음", symbol: "-", rarity: "N" },
      { id: "under-eye-dot", label: "눈밑 점", symbol: ".", rarity: "R", asset: "./assets/avatar/beauty-under-eye-dot.svg" },
      { id: "lip-dot", label: "입술 점", symbol: ".", rarity: "R" },
      { id: "star", label: "별 포인트", symbol: "☆", rarity: "SR", asset: "./assets/avatar/beauty-star.png?v=20260502-029", thumb: "./assets/avatar/thumbs/beauty-star.png?v=20260502-029" },
      { id: "blush", label: "볼터치", symbol: "♡", rarity: "SR", asset: "./assets/avatar/beauty-blush.png?v=20260502-029", thumb: "./assets/avatar/thumbs/beauty-blush.png?v=20260502-029" },
      { id: "void", label: "V 포인트", symbol: "V", rarity: "SSR" },
    ],
    accessory: [
      { id: "none", label: "없음", symbol: "-", rarity: "N" },
      { id: "silver-ear", label: "실버 귀걸이", symbol: "◇", rarity: "R", asset: "./assets/avatar/accessory-silver-ear.png?v=20260502-029", thumb: "./assets/avatar/thumbs/accessory-silver-ear.png?v=20260502-029" },
      { id: "cross-ear", label: "크로스 귀걸이", symbol: "†", rarity: "SR", asset: "./assets/avatar/accessory-cross-ear.png?v=20260502-029", thumb: "./assets/avatar/thumbs/accessory-cross-ear.png?v=20260502-029" },
      { id: "round-glasses", label: "동그란 안경", symbol: "○", rarity: "R", asset: "./assets/avatar/accessory-round-glasses.png?v=20260502-029", thumb: "./assets/avatar/thumbs/accessory-round-glasses.png?v=20260502-029" },
      { id: "black-mask", label: "블랙 마스크", symbol: "▰", rarity: "SR", asset: "./assets/avatar/accessory-black-mask.png?v=20260502-029", thumb: "./assets/avatar/thumbs/accessory-black-mask.png?v=20260502-029" },
      { id: "heart-glasses", label: "하트 안경", symbol: "♡", rarity: "SSR", asset: "./assets/avatar/accessory-heart-glasses.png?v=20260502-029", thumb: "./assets/avatar/thumbs/accessory-heart-glasses.png?v=20260502-029" },
      { id: "stage-mic", label: "인이어 마이크", symbol: "♪", rarity: "SR", asset: "./assets/avatar/accessory-stage-mic.png?v=20260502-029", thumb: "./assets/avatar/thumbs/accessory-stage-mic.png?v=20260502-029" },
    ],
    top: [
      { id: "underwear", label: "기본 이너", symbol: "IN", rarity: "N", color: "#f7f3ea", trim: "#d9c8a4" },
      { id: "stage-black", label: "블랙 무대복", symbol: "JK", rarity: "R", color: "#20232b", trim: "#ff4d6d", asset: "./assets/avatar/top-stage-black.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-stage-black.png?v=20260502-030" },
      { id: "v01d-red", label: "V01D 레드 셔츠", symbol: "V", rarity: "SR", color: "#b51d2a", trim: "#15171c", asset: "./assets/avatar/top-v01d-red.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-v01d-red.png?v=20260502-030" },
      { id: "white-vocal", label: "화이트 보컬 재킷", symbol: "W", rarity: "SR", color: "#f0f2f6", trim: "#20232b", asset: "./assets/avatar/top-white-vocal.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-white-vocal.png?v=20260502-030" },
      { id: "yellow-plaid", label: "옐로 플래드", symbol: "P", rarity: "R", color: "#ffd166", trim: "#20232b", asset: "./assets/avatar/top-yellow-plaid.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-yellow-plaid.png?v=20260502-030" },
      { id: "stripe-bass", label: "레드 스트라이프", symbol: "B", rarity: "SR", color: "#ff4d6d", trim: "#111318", asset: "./assets/avatar/top-stripe-bass.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-stripe-bass.png?v=20260502-030" },
      { id: "school", label: "스쿨 셔츠", symbol: "S", rarity: "N", color: "#e8eef8", trim: "#6aa7ff", asset: "./assets/avatar/top-school.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-school.png?v=20260502-030" },
      { id: "street", label: "스트릿 후디", symbol: "ST", rarity: "R", color: "#b8f35f", trim: "#20232b", asset: "./assets/avatar/top-street.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-street.png?v=20260502-030" },
      { id: "varsity", label: "바시티 재킷", symbol: "VS", rarity: "R", color: "#4de0bd", trim: "#f7f3ea", asset: "./assets/avatar/top-varsity.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-varsity.png?v=20260502-030" },
      { id: "royal", label: "로열 무대복", symbol: "R", rarity: "SSR", color: "#ffd166", trim: "#7c1d2d", asset: "./assets/avatar/top-royal.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-royal.png?v=20260502-030" },
      { id: "denim", label: "데님 재킷", symbol: "D", rarity: "N", color: "#4f7fbf", trim: "#f7f3ea", asset: "./assets/avatar/top-denim.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-denim.png?v=20260502-030" },
      { id: "techwear", label: "테크웨어", symbol: "T", rarity: "SSR", color: "#28243d", trim: "#9b7bff", asset: "./assets/avatar/top-techwear.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-techwear.png?v=20260502-030" },
      { id: "holo-stage", label: "홀로 스테이지", symbol: "H", rarity: "SSR", color: "#4de0bd", trim: "#9b7bff", asset: "./assets/avatar/top-holo-stage.png?v=20260502-030", thumb: "./assets/avatar/thumbs/top-holo-stage.png?v=20260502-030" },
    ],
    pants: [
      { id: "underwear", label: "기본 하의", symbol: "IN", rarity: "N", color: "#f7f3ea", asset: "./assets/avatar/pants-underwear.png?v=20260502-030", thumb: "./assets/avatar/thumbs/pants-underwear.png?v=20260502-030" },
      { id: "black-skinny", label: "블랙 스키니", symbol: "BK", rarity: "N", color: "#17191f", asset: "./assets/avatar/pants-black-skinny.png?v=20260502-030", thumb: "./assets/avatar/thumbs/pants-black-skinny.png?v=20260502-030" },
      { id: "ripped-black", label: "찢청 블랙", symbol: "RB", rarity: "R", color: "#20232b", asset: "./assets/avatar/pants-ripped-black.png?v=20260502-030", thumb: "./assets/avatar/thumbs/pants-ripped-black.png?v=20260502-030" },
      { id: "denim-blue", label: "블루 데님", symbol: "DN", rarity: "N", color: "#315d93", asset: "./assets/avatar/pants-denim-blue.png?v=20260502-030", thumb: "./assets/avatar/thumbs/pants-denim-blue.png?v=20260502-030" },
      { id: "cargo", label: "카고 팬츠", symbol: "CG", rarity: "R", color: "#4a4a3e", asset: "./assets/avatar/pants-cargo.png?v=20260502-030", thumb: "./assets/avatar/thumbs/pants-cargo.png?v=20260502-030" },
      { id: "stage-leather", label: "스테이지 레더", symbol: "LT", rarity: "SR", color: "#101114", asset: "./assets/avatar/pants-stage-leather.png?v=20260502-030", thumb: "./assets/avatar/thumbs/pants-stage-leather.png?v=20260502-030" },
      { id: "pleats", label: "플리츠 스커트", symbol: "PL", rarity: "SR", color: "#252a36", asset: "./assets/avatar/pants-pleats.png?v=20260502-030", thumb: "./assets/avatar/thumbs/pants-pleats.png?v=20260502-030" },
      { id: "holo", label: "홀로 팬츠", symbol: "HO", rarity: "SSR", color: "#5966c9", asset: "./assets/avatar/pants-holo.png?v=20260502-030", thumb: "./assets/avatar/thumbs/pants-holo.png?v=20260502-030" },
    ],
    shoes: [
      { id: "bare", label: "기본 양말", symbol: "SO", rarity: "N", color: "#f7f3ea", asset: "./assets/avatar/shoes-bare.png?v=20260502-030", thumb: "./assets/avatar/thumbs/shoes-bare.png?v=20260502-030" },
      { id: "black-boots", label: "블랙 부츠", symbol: "BT", rarity: "R", color: "#101114", asset: "./assets/avatar/shoes-black-boots.png?v=20260502-030", thumb: "./assets/avatar/thumbs/shoes-black-boots.png?v=20260502-030" },
      { id: "white-sneakers", label: "화이트 스니커즈", symbol: "WS", rarity: "N", color: "#f1f4f8", asset: "./assets/avatar/shoes-white-sneakers.png?v=20260502-030", thumb: "./assets/avatar/thumbs/shoes-white-sneakers.png?v=20260502-030" },
      { id: "red-boots", label: "레드 부츠", symbol: "RB", rarity: "SR", color: "#b51d2a", asset: "./assets/avatar/shoes-red-boots.png?v=20260502-030", thumb: "./assets/avatar/thumbs/shoes-red-boots.png?v=20260502-030" },
      { id: "platform", label: "플랫폼 슈즈", symbol: "PF", rarity: "SR", color: "#252a36", asset: "./assets/avatar/shoes-platform.png?v=20260502-030", thumb: "./assets/avatar/thumbs/shoes-platform.png?v=20260502-030" },
      { id: "holo", label: "홀로 슈즈", symbol: "HS", rarity: "SSR", color: "#4de0bd", asset: "./assets/avatar/shoes-holo.png?v=20260502-030", thumb: "./assets/avatar/thumbs/shoes-holo.png?v=20260502-030" },
    ],
    outfit: [
      { id: "stage-black", label: "블랙 무대복", symbol: "JK", rarity: "R", color: "#20232b" },
      { id: "v01d-red", label: "V01D 레드 셔츠", symbol: "V", rarity: "SR", color: "#b51d2a" },
    ],
    hat: [
      { id: "none", label: "없음", symbol: "-", rarity: "N" },
      { id: "black-beanie", label: "블랙 비니", symbol: "BN", rarity: "R" },
      { id: "cat-ear", label: "고양이 귀", symbol: "⌃", rarity: "SR" },
      { id: "mini-crown", label: "미니 왕관", symbol: "♛", rarity: "SSR" },
      { id: "stage-pin", label: "스테이지 핀", symbol: "✦", rarity: "R" },
      { id: "headset", label: "인이어 헤드셋", symbol: "♪", rarity: "SR" },
      { id: "sunglasses", label: "선글라스", symbol: "▰", rarity: "SR" },
      { id: "fan-ribbon", label: "팬덤 리본", symbol: "♡", rarity: "SSR" },
    ],
    face: [
      { id: "base-m", label: "남자 기본 얼굴", symbol: "M", rarity: "N", asset: "./assets/avatar/face-base-m.png?v=20260502-030", thumb: "./assets/avatar/thumbs/face-base-m.png?v=20260502-030" },
      { id: "base-f", label: "여자 기본 얼굴", symbol: "F", rarity: "N", asset: "./assets/avatar/face-base-f.png?v=20260502-030", thumb: "./assets/avatar/thumbs/face-base-f.png?v=20260502-030" },
      { id: "warm", label: "웜톤 얼굴", symbol: "W", rarity: "N", asset: "./assets/avatar/face-warm.png?v=20260502-030", thumb: "./assets/avatar/thumbs/face-warm.png?v=20260502-030" },
      { id: "cool", label: "쿨톤 얼굴", symbol: "C", rarity: "R", asset: "./assets/avatar/face-cool.png?v=20260502-030", thumb: "./assets/avatar/thumbs/face-cool.png?v=20260502-030" },
      { id: "tan", label: "태닝 얼굴", symbol: "T", rarity: "R", asset: "./assets/avatar/face-tan.png?v=20260502-030", thumb: "./assets/avatar/thumbs/face-tan.png?v=20260502-030" },
      { id: "porcelain", label: "포슬린 얼굴", symbol: "P", rarity: "SR", asset: "./assets/avatar/face-porcelain.png?v=20260502-030", thumb: "./assets/avatar/thumbs/face-porcelain.png?v=20260502-030" },
    ],
    item: [
      { id: "none", label: "없음", symbol: "-", rarity: "N", asset: "./assets/avatar/item-none.png?v=20260502-030", thumb: "./assets/avatar/thumbs/item-none.png?v=20260502-030" },
      { id: "lightstick", label: "응원봉", symbol: "✦", rarity: "N", asset: "./assets/avatar/item-lightstick.png?v=20260502-030", thumb: "./assets/avatar/thumbs/item-lightstick.png?v=20260502-030" },
      { id: "mic", label: "마이크", symbol: "♪", rarity: "R", asset: "./assets/avatar/item-mic.png?v=20260502-030", thumb: "./assets/avatar/thumbs/item-mic.png?v=20260502-030" },
      { id: "photocard", label: "포카", symbol: "▣", rarity: "R", asset: "./assets/avatar/item-photocard.png?v=20260502-030", thumb: "./assets/avatar/thumbs/item-photocard.png?v=20260502-030" },
      { id: "drumstick", label: "드럼스틱", symbol: "╱", rarity: "SR", asset: "./assets/avatar/item-drumstick.png?v=20260502-030", thumb: "./assets/avatar/thumbs/item-drumstick.png?v=20260502-030" },
      { id: "keytar", label: "키타", symbol: "▤", rarity: "SR", asset: "./assets/avatar/item-keytar.png?v=20260502-030", thumb: "./assets/avatar/thumbs/item-keytar.png?v=20260502-030" },
      { id: "guitar-pick", label: "기타 피크", symbol: "◆", rarity: "R", asset: "./assets/avatar/item-guitar-pick.png?v=20260502-030", thumb: "./assets/avatar/thumbs/item-guitar-pick.png?v=20260502-030" },
      { id: "bass-pick", label: "베이스 피크", symbol: "◇", rarity: "R", asset: "./assets/avatar/item-bass-pick.png?v=20260502-030", thumb: "./assets/avatar/thumbs/item-bass-pick.png?v=20260502-030" },
      { id: "camera", label: "직캠 카메라", symbol: "◎", rarity: "SR", asset: "./assets/avatar/item-camera.png?v=20260502-030", thumb: "./assets/avatar/thumbs/item-camera.png?v=20260502-030" },
      { id: "star-bag", label: "별 가방", symbol: "☆", rarity: "SSR" },
      { id: "fan-letter", label: "팬레터", symbol: "✉", rarity: "SR" },
    ],
    back: [
      { id: "none", label: "없음", symbol: "-", rarity: "N" },
      { id: "amp", label: "앰프", symbol: "▣", rarity: "R" },
      { id: "spotlight", label: "스포트라이트", symbol: "⌁", rarity: "SR" },
      { id: "neon-sign", label: "네온 사인", symbol: "V", rarity: "SSR" },
      { id: "photo-wall", label: "포토월", symbol: "▥", rarity: "SR" },
      { id: "concert-light", label: "콘서트 조명", symbol: "✦", rarity: "SSR" },
      { id: "speaker-stack", label: "스피커 스택", symbol: "▦", rarity: "R" },
    ],
    aura: [
      { id: "sparkle", label: "스파클", symbol: "✦", rarity: "N", color: "#ffd166" },
      { id: "neon", label: "네온", symbol: "▱", rarity: "R", color: "#4de0bd" },
      { id: "heart", label: "하트", symbol: "♡", rarity: "SR", color: "#ff4d6d" },
      { id: "star", label: "별빛", symbol: "☆", rarity: "SR", color: "#6aa7ff" },
      { id: "spotlight", label: "스포트라이트", symbol: "⌁", rarity: "R", color: "#f7f3ea" },
      { id: "purple", label: "퍼플 글로우", symbol: "◇", rarity: "SSR", color: "#9b7bff" },
      { id: "void-red", label: "V01D 레드 오라", symbol: "V", rarity: "SSR", color: "#ff4d6d" },
      { id: "holo-ring", label: "홀로 링", symbol: "◎", rarity: "SSR", color: "#4de0bd" },
    ],
  },
  idolGroups: [
    {
      id: "v01d",
      type: "band",
      name: "V01D",
      tags: ["공식 등록", "5인조 밴드", "IX Entertainment"],
      owned: true,
      status: "registered",
      members: [
        { name: "송유찬", birth: "1995.01.09", nationality: "KR", roles: ["리더", "드럼"] },
        { name: "조주연", birth: "2000.05.08", nationality: "KR", roles: ["메인보컬"] },
        { name: "케빈박", birth: "2001.06.21", nationality: "US", roles: ["키보드", "보컬"] },
        { name: "정지섭", birth: "2001.11.11", nationality: "KR", roles: ["기타", "보컬"] },
        { name: "신노스케", birth: "2005.10.24", nationality: "JP", roles: ["베이스"] },
      ],
      debut: "2026-03-11",
      debutAlbum: "01",
    },
    { id: "bts", type: "boy", name: "BTS", tags: ["레전드", "퍼포먼스", "글로벌"] },
    { id: "seventeen", type: "boy", name: "SEVENTEEN", tags: ["자체제작", "칼군무", "예능감"] },
    { id: "stray-kids", type: "boy", name: "Stray Kids", tags: ["강한 사운드", "퍼포먼스", "글로벌"] },
    { id: "enhypen", type: "boy", name: "ENHYPEN", tags: ["서사", "퍼포먼스", "팬덤"] },
    { id: "txt", type: "boy", name: "TXT", tags: ["청량", "콘셉트", "스토리"] },
    { id: "blackpink", type: "girl", name: "BLACKPINK", tags: ["아이콘", "패션", "글로벌"] },
    { id: "twice", type: "girl", name: "TWICE", tags: ["히트곡", "팬서비스", "콘서트"] },
    { id: "aespa", type: "girl", name: "aespa", tags: ["세계관", "보컬", "콘셉트"] },
    { id: "ive", type: "girl", name: "IVE", tags: ["자기확신", "비주얼", "후렴"] },
    { id: "le-sserafim", type: "girl", name: "LE SSERAFIM", tags: ["퍼포먼스", "당당함", "무대"] },
  ],
  themes: [
    { id: "neon-basement", label: "네온 지하실", vibe: "어두운 조명과 형광 사인", accent: "#4de0bd" },
    { id: "after-class", label: "교실 after", vibe: "방과 후 책상 사이에서 하는 몰래 게임", accent: "#ffd166" },
    { id: "space-station", label: "우주 정거장", vibe: "둥둥 뜨는 회의실과 차가운 조명", accent: "#6aa7ff" },
    { id: "retro-gym", label: "레트로 체육관", vibe: "응원봉과 확성기가 있는 체육대회", accent: "#ff4d6d" },
    { id: "idol-backstage", label: "아이돌 백스테이지", vibe: "대기실, 포토월, 무대 전 긴장감", accent: "#9b7bff" },
  ],
  notices: [
    {
      id: "v01d-registered",
      type: "artist",
      groupId: "v01d",
      date: "2026-05-01",
      title: "V01D 등록 완료",
      body: "남자 5인조 밴드그룹 V01D가 공식 질문 테마로 등록되었습니다.",
    },
    {
      id: "kpop-pack-open",
      type: "pack",
      packId: "kpop",
      date: "2026-05-01",
      title: "케이팝 팬덤 질문팩 추가",
      body: "최애, 컴백, 콘서트, 포카 주제로 플레이할 수 있습니다.",
    },
  ],
  packs: [
    {
      id: "kpop",
      name: "케이팝 팬덤",
      themeSource: "idolGroups",
      defaultQuestionTheme: "v01d",
      count: 52,
      status: "팬덤",
      tone: "최애 얘기만으로 바로 싸움 나는 질문",
      rounds: [
        {
          title: "컴백",
          innocent: "컴백 첫날 팬들이 제일 먼저 확인하는 건?",
          fake: "컴백 한참 뒤에 봐도 되는 건?",
          answers: ["뮤비", "음원 순위", "직캠", "포카 시세", "비하인드", "스케줄표"],
          botAnswers: ["뮤비", "음원 순위", "직캠", "응원법", "쇼케이스"],
          fakeAnswers: ["비하인드", "스케줄표", "자막 인터뷰", "굿즈 재고"],
        },
        {
          title: "최애",
          innocent: "최애 입덕 포인트로 강한 건?",
          fake: "최애 탈덕 방어에 필요한 건?",
          answers: ["무대 표정", "라이브", "팬사랑", "예능감", "소통", "실물 후기"],
          botAnswers: ["무대 표정", "라이브", "팬사랑", "예능감"],
          fakeAnswers: ["소통", "실물 후기", "꾸준한 활동", "좋은 스타일링"],
        },
        {
          title: "콘서트",
          innocent: "콘서트 가기 전에 꼭 챙길 건?",
          fake: "콘서트 끝나고 챙기면 되는 건?",
          answers: ["티켓", "응원봉", "보조배터리", "슬로건", "후기", "굿즈 정리"],
          botAnswers: ["티켓", "응원봉", "보조배터리", "슬로건"],
          fakeAnswers: ["후기", "굿즈 정리", "사진 백업", "셋리스트 복습"],
        },
        {
          title: "포카",
          innocent: "포카 교환할 때 제일 중요한 건?",
          fake: "포카 보관할 때 제일 중요한 건?",
          answers: ["하자 확인", "시세", "인증샷", "직거래 장소", "슬리브", "탑로더"],
          botAnswers: ["하자 확인", "시세", "인증샷", "직거래 장소"],
          fakeAnswers: ["슬리브", "탑로더", "습기 방지", "바인더"],
        },
      ],
    },
    {
      id: "daily",
      name: "일상",
      count: 48,
      status: "기본",
      tone: "처음 하는 친구도 바로 답하는 질문",
      questionThemes: [
        { id: "night-snack", name: "야식", tags: ["편의점", "배달"] },
        { id: "weekend", name: "주말", tags: ["친구", "휴식"] },
        { id: "chat", name: "단톡", tags: ["말투", "밈"] },
      ],
      rounds: [
        {
          title: "편의점",
          themes: ["night-snack"],
          innocent: "편의점에서 자주 사는 야식은?",
          fake: "편의점에서 굳이 안 사는 음식은?",
          answers: ["삼각김밥", "컵라면", "핫바", "제로콜라", "생수", "초코우유"],
          botAnswers: ["삼각김밥", "컵라면", "핫바", "도시락", "떡볶이"],
          fakeAnswers: ["생수", "껌", "샐러드", "견과류"],
        },
        {
          title: "배달",
          themes: ["night-snack"],
          innocent: "여럿이 시키기 좋은 배달 메뉴는?",
          fake: "혼자 시키기 좋은 배달 메뉴는?",
          answers: ["치킨", "피자", "마라탕", "떡볶이", "초밥", "햄버거"],
          botAnswers: ["치킨", "피자", "마라탕", "떡볶이", "족발"],
          fakeAnswers: ["햄버거", "초밥", "샐러드", "덮밥"],
        },
        {
          title: "주말",
          themes: ["weekend"],
          innocent: "친구들이랑 주말에 하기 좋은 건?",
          fake: "혼자 주말에 하기 좋은 건?",
          answers: ["방탈출", "맛집", "보드게임", "노래방", "영화", "낮잠"],
          botAnswers: ["방탈출", "맛집", "보드게임", "노래방", "카페"],
          fakeAnswers: ["낮잠", "넷플릭스", "산책", "게임"],
        },
        {
          title: "단톡",
          themes: ["chat"],
          innocent: "단톡방에서 반응 좋은 말투는?",
          fake: "단톡방에서 분위기 식는 말투는?",
          answers: ["짧고 웃기게", "리액션 크게", "짤 보내기", "바로 답장", "읽씹", "팩폭"],
          botAnswers: ["짧고 웃기게", "리액션 크게", "짤 보내기", "바로 답장"],
          fakeAnswers: ["읽씹", "팩폭", "장문 훈수", "갑분진지"],
        },
      ],
    },
    {
      id: "romance",
      name: "연애/썸",
      count: 36,
      status: "인기",
      tone: "대답만 봐도 놀림거리가 생기는 질문",
      questionThemes: [
        { id: "date", name: "데이트", tags: ["첫만남", "장소"] },
        { id: "texting", name: "카톡", tags: ["답장", "시그널"] },
        { id: "gift", name: "선물", tags: ["부담", "취향"] },
      ],
      rounds: [
        {
          title: "첫 데이트",
          themes: ["date"],
          innocent: "첫 데이트 장소로 좋은 곳은?",
          fake: "혼자 시간 보내기 좋은 곳은?",
          answers: ["영화관", "카페", "한강", "전시회", "PC방", "집"],
          botAnswers: ["영화관", "카페", "한강", "전시회", "맛집"],
          fakeAnswers: ["집", "PC방", "서점", "산책"],
        },
        {
          title: "답장",
          themes: ["texting"],
          innocent: "호감 있을 때 보내기 좋은 답장은?",
          fake: "관심 없을 때 보내기 쉬운 답장은?",
          answers: ["ㅋㅋㅋㅋ", "언제 볼래?", "나도 좋아", "사진 보내기", "응", "바쁨"],
          botAnswers: ["ㅋㅋㅋㅋ", "언제 볼래?", "나도 좋아", "사진 보내기"],
          fakeAnswers: ["응", "바쁨", "나중에", "읽고 답 없음"],
        },
        {
          title: "선물",
          themes: ["gift"],
          innocent: "가볍게 받으면 기분 좋은 선물은?",
          fake: "받으면 조금 부담스러운 선물은?",
          answers: ["커피 쿠폰", "디저트", "향수", "꽃", "커플템", "손편지"],
          botAnswers: ["커피 쿠폰", "디저트", "꽃", "키링"],
          fakeAnswers: ["커플템", "비싼 향수", "손편지", "옷"],
        },
      ],
    },
    {
      id: "party",
      name: "MT/술자리",
      count: 42,
      status: "파티",
      tone: "짧고 웃긴 단체용 질문",
      questionThemes: [
        { id: "trip", name: "여행", tags: ["MT", "숙소"] },
        { id: "karaoke", name: "노래방", tags: ["첫곡", "떼창"] },
        { id: "drinking", name: "술게임", tags: ["처음", "친한사이"] },
      ],
      rounds: [
        {
          title: "여행",
          themes: ["trip"],
          innocent: "친구들이랑 여행 가면 꼭 하는 일은?",
          fake: "혼자 여행 가면 꼭 하는 일은?",
          answers: ["맛집 찾기", "사진 찍기", "숙소에서 쉬기", "야시장", "카페 투어", "늦잠"],
          botAnswers: ["맛집 찾기", "사진 찍기", "야시장", "카페 투어", "기념품 쇼핑"],
          fakeAnswers: ["늦잠", "혼밥", "숙소에서 쉬기", "책 읽기"],
        },
        {
          title: "노래방",
          themes: ["karaoke"],
          innocent: "노래방 첫 곡으로 괜찮은 노래 스타일은?",
          fake: "노래방 마지막 곡으로 괜찮은 노래 스타일은?",
          answers: ["발라드", "댄스곡", "아이돌곡", "랩", "OST", "떼창곡"],
          botAnswers: ["댄스곡", "아이돌곡", "신나는 곡", "떼창곡", "아는 노래"],
          fakeAnswers: ["발라드", "이별 노래", "고음곡", "잔잔한 OST"],
        },
        {
          title: "술게임",
          themes: ["drinking"],
          innocent: "처음 만난 사람들과 하기 쉬운 술게임은?",
          fake: "친한 사람끼리 해야 덜 민망한 술게임은?",
          answers: ["369", "눈치게임", "딸기게임", "훈민정음", "진실게임", "이미지게임"],
          botAnswers: ["369", "눈치게임", "딸기게임", "훈민정음"],
          fakeAnswers: ["진실게임", "이미지게임", "밸런스게임", "왕게임"],
        },
        {
          title: "숙소",
          themes: ["trip"],
          innocent: "MT 숙소에서 제일 먼저 정할 건?",
          fake: "MT 숙소에서 마지막에 정해도 되는 건?",
          answers: ["방 배정", "장보기", "저녁 메뉴", "술 담당", "아침 메뉴", "청소 순서"],
          botAnswers: ["방 배정", "장보기", "저녁 메뉴", "술 담당"],
          fakeAnswers: ["아침 메뉴", "청소 순서", "귀가 시간", "사진 정리"],
        },
      ],
    },
    {
      id: "campus",
      name: "학교/동아리",
      count: 40,
      status: "친구",
      tone: "같은 반, 동아리, 과모임에서 바로 통하는 질문",
      questionThemes: [
        { id: "classroom", name: "교실", tags: ["수업", "쉬는시간"] },
        { id: "club", name: "동아리", tags: ["선후배", "회식 전"] },
        { id: "exam", name: "시험기간", tags: ["벼락치기", "팀플"] },
      ],
      rounds: [
        { title: "쉬는시간", themes: ["classroom"], innocent: "쉬는시간에 친구들이랑 하기 좋은 건?", fake: "수업 시작 직전에 하기 좋은 건?", answers: ["매점", "수다", "화장실", "릴스 보기", "물 마시기", "자리 정리"], botAnswers: ["매점", "수다", "화장실", "릴스 보기"], fakeAnswers: ["물 마시기", "자리 정리", "교재 꺼내기", "필기구 찾기"] },
        { title: "팀플", themes: ["exam"], innocent: "팀플에서 제일 먼저 정해야 하는 건?", fake: "팀플 끝나고 정리해도 되는 건?", answers: ["역할", "마감", "자료조사", "발표자", "후기", "파일명"], botAnswers: ["역할", "마감", "자료조사", "발표자"], fakeAnswers: ["후기", "파일명", "표지 디자인", "뒷풀이"] },
        { title: "동아리", themes: ["club"], innocent: "신입 부원에게 먼저 알려줄 건?", fake: "오래 다닌 부원만 알아도 되는 건?", answers: ["활동 시간", "단톡방", "회비", "장소", "전통", "뒷풀이 맛집"], botAnswers: ["활동 시간", "단톡방", "회비", "장소"], fakeAnswers: ["전통", "뒷풀이 맛집", "옛날 에피소드", "운영진 별명"] },
        { title: "시험기간", themes: ["exam"], innocent: "시험 전날 제일 도움 되는 건?", fake: "시험 끝나고 해도 되는 건?", answers: ["요약본", "기출", "암기", "잠", "채점", "뒷풀이"], botAnswers: ["요약본", "기출", "암기", "잠"], fakeAnswers: ["채점", "뒷풀이", "책 정리", "다음 계획"] },
      ],
    },
    {
      id: "work",
      name: "회사/알바",
      count: 44,
      status: "공감",
      tone: "회사, 알바, 프로젝트에서 나오는 현실적인 질문",
      questionThemes: [
        { id: "office", name: "사무실", tags: ["회의", "메신저"] },
        { id: "part-time", name: "알바", tags: ["매장", "교대"] },
        { id: "project", name: "프로젝트", tags: ["마감", "역할"] },
      ],
      rounds: [
        { title: "회의", themes: ["office"], innocent: "회의 전에 준비하면 좋은 건?", fake: "회의 끝나고 정리해도 되는 건?", answers: ["안건", "자료", "질문", "시간 확인", "회의록", "점심 메뉴"], botAnswers: ["안건", "자료", "질문", "시간 확인"], fakeAnswers: ["회의록", "점심 메뉴", "캘린더 정리", "잡담"] },
        { title: "알바 교대", themes: ["part-time"], innocent: "교대 전에 꼭 확인할 건?", fake: "퇴근 후에 확인해도 되는 건?", answers: ["재고", "포스", "인수인계", "청소 상태", "월급날", "단톡"], botAnswers: ["재고", "포스", "인수인계", "청소 상태"], fakeAnswers: ["월급날", "단톡", "후기", "유니폼 세탁"] },
        { title: "마감", themes: ["project"], innocent: "마감 직전에 제일 위험한 건?", fake: "마감 끝나고 해도 되는 건?", answers: ["오타", "누락", "공유 안 함", "버그", "회고", "폴더 정리"], botAnswers: ["오타", "누락", "공유 안 함", "버그"], fakeAnswers: ["회고", "폴더 정리", "성과 캡처", "감상"] },
        { title: "메신저", themes: ["office"], innocent: "업무 메신저에서 바로 답해야 하는 건?", fake: "나중에 답해도 되는 건?", answers: ["긴급 요청", "장애", "회의 변경", "승인", "잡담", "이모지"], botAnswers: ["긴급 요청", "장애", "회의 변경", "승인"], fakeAnswers: ["잡담", "이모지", "점심 얘기", "링크 공유"] },
      ],
    },
    {
      id: "creator",
      name: "방송/스트리머",
      count: 40,
      status: "방송",
      tone: "스트리머와 시청자가 같이 보기 좋은 질문",
      questionThemes: [
        { id: "stream-chat", name: "채팅", tags: ["도네", "밈"] },
        { id: "content", name: "콘텐츠", tags: ["합방", "기획"] },
        { id: "fan", name: "팬덤", tags: ["구독", "클립"] },
      ],
      rounds: [
        { title: "채팅창", themes: ["stream-chat"], innocent: "채팅창 분위기를 살리는 말은?", fake: "채팅창 분위기를 식히는 말은?", answers: ["ㅋㅋㅋㅋ", "레전드", "클립각", "나이스", "훈수", "비교"], botAnswers: ["ㅋㅋㅋㅋ", "레전드", "클립각", "나이스"], fakeAnswers: ["훈수", "비교", "스포", "갑분싸 질문"] },
        { title: "합방", themes: ["content"], innocent: "합방에서 먼저 맞춰야 하는 건?", fake: "합방 끝나고 봐도 되는 건?", answers: ["시간", "게임", "룰", "음량", "클립", "후기"], botAnswers: ["시간", "게임", "룰", "음량"], fakeAnswers: ["클립", "후기", "썸네일", "댓글"] },
        { title: "도네", themes: ["stream-chat"], innocent: "도네로 보내면 반응 좋은 건?", fake: "도네로 보내면 부담스러운 건?", answers: ["짧은 드립", "응원", "축하", "리액션 요청", "장문", "개인 질문"], botAnswers: ["짧은 드립", "응원", "축하", "리액션 요청"], fakeAnswers: ["장문", "개인 질문", "비교", "무리한 요청"] },
        { title: "팬심", themes: ["fan"], innocent: "팬이 오래 남게 만드는 건?", fake: "새 유입이 바로 보기 힘든 건?", answers: ["꾸준함", "소통", "재미", "분위기", "내부 밈", "옛날 사건"], botAnswers: ["꾸준함", "소통", "재미", "분위기"], fakeAnswers: ["내부 밈", "옛날 사건", "긴 공지", "복잡한 룰"] },
      ],
    },
    {
      id: "game",
      name: "게임/랭크",
      count: 40,
      status: "게임",
      tone: "게이머끼리 바로 싸움 날 수 있는 질문",
      questionThemes: [
        { id: "rank", name: "랭크", tags: ["티어", "멘탈"] },
        { id: "party-game", name: "파티게임", tags: ["친구", "웃김"] },
        { id: "build", name: "세팅", tags: ["장비", "빌드"] },
      ],
      rounds: [
        { title: "랭크", themes: ["rank"], innocent: "랭크 올릴 때 제일 중요한 건?", fake: "랭크 떨어질 때 제일 흔한 핑계는?", answers: ["멘탈", "피지컬", "맵 이해", "소통", "팀운", "렉"], botAnswers: ["멘탈", "피지컬", "맵 이해", "소통"], fakeAnswers: ["팀운", "렉", "매칭", "컨디션"] },
        { title: "파티게임", themes: ["party-game"], innocent: "친구랑 하면 웃긴 게임 요소는?", fake: "혼자 하면 편한 게임 요소는?", answers: ["배신", "랜덤", "벌칙", "음성채팅", "파밍", "스토리"], botAnswers: ["배신", "랜덤", "벌칙", "음성채팅"], fakeAnswers: ["파밍", "스토리", "옵션 조정", "튜토리얼"] },
        { title: "장비", themes: ["build"], innocent: "게임 시작 전 세팅해야 하는 건?", fake: "게임 끝나고 바꿔도 되는 건?", answers: ["감도", "키세팅", "음량", "그래픽", "닉네임", "프로필"], botAnswers: ["감도", "키세팅", "음량", "그래픽"], fakeAnswers: ["닉네임", "프로필", "스킨", "칭호"] },
        { title: "디스코드", themes: ["rank", "party-game"], innocent: "게임 중 음성으로 바로 말해야 하는 건?", fake: "게임 끝나고 말해도 되는 건?", answers: ["위치", "위험", "전략", "궁극기", "감상", "리플레이"], botAnswers: ["위치", "위험", "전략", "궁극기"], fakeAnswers: ["감상", "리플레이", "하이라이트", "칭찬"] },
      ],
    },
    {
      id: "travel-food",
      name: "여행/맛집",
      count: 40,
      status: "힐링",
      tone: "여행 계획과 맛집 취향에서 갈리는 질문",
      questionThemes: [
        { id: "trip-plan", name: "여행계획", tags: ["숙소", "동선"] },
        { id: "food", name: "맛집", tags: ["메뉴", "웨이팅"] },
        { id: "photo", name: "사진", tags: ["인생샷", "기록"] },
      ],
      rounds: [
        { title: "숙소", themes: ["trip-plan"], innocent: "여행 숙소 고를 때 중요한 건?", fake: "숙소 도착 후 봐도 되는 건?", answers: ["위치", "가격", "청결", "후기", "조명", "어메니티"], botAnswers: ["위치", "가격", "청결", "후기"], fakeAnswers: ["조명", "어메니티", "뷰 사진", "인테리어"] },
        { title: "맛집", themes: ["food"], innocent: "맛집 고를 때 믿을 만한 건?", fake: "맛집 다녀온 뒤 남는 건?", answers: ["리뷰", "사진", "현지인 추천", "메뉴판", "영수증", "스토리"], botAnswers: ["리뷰", "사진", "현지인 추천", "메뉴판"], fakeAnswers: ["영수증", "스토리", "기념 사진", "후기"] },
        { title: "사진", themes: ["photo"], innocent: "여행 사진 찍기 전에 보는 건?", fake: "여행 사진 찍은 뒤 하는 건?", answers: ["구도", "빛", "배경", "표정", "보정", "업로드"], botAnswers: ["구도", "빛", "배경", "표정"], fakeAnswers: ["보정", "업로드", "앨범 정리", "태그"] },
        { title: "동선", themes: ["trip-plan"], innocent: "여행 첫날에 잡기 좋은 일정은?", fake: "여행 마지막 날에 잡기 좋은 일정은?", answers: ["가까운 맛집", "숙소 주변", "가벼운 산책", "야시장", "기념품", "짐 정리"], botAnswers: ["가까운 맛집", "숙소 주변", "가벼운 산책", "야시장"], fakeAnswers: ["기념품", "짐 정리", "공항 근처", "체크아웃"] },
      ],
    },
  ],
  locales: {
    ja: {
      playerNames: ["ミンソ", "ドユン", "ジウ", "ハジュン", "ソヨン", "ユナ"],
      frames: {
        lime: "ライム",
        coral: "コーラル",
        gold: "ゴールド",
        stage: "ステージ",
        holo: "ホログラム",
        heart: "ハート",
      },
      biasStyles: {
        "main-vocal": { label: "メボ", detail: "澄んだボーカル、ハートマイク" },
        "main-dancer": { label: "メインダンサー", detail: "ダンスブレイク、シルバーチェーン" },
        center: { label: "センター", detail: "エンディング妖精、星グリッター" },
        rapper: { label: "ラッパー", detail: "強めのラップ、ブラックキャップ" },
      },
      dressUp: {
        hair: {
          short: "ショート",
          wave: "ウェーブ",
          silver: "シルバー",
          black: "ブラック",
          "mint-twin": "ミントツイン",
          "pink-bang": "ピンク前髪",
          "gold-tail": "ゴールドポニー",
          violet: "バイオレット",
        },
        outfit: {
          "stage-black": "黒ステージ衣装",
          school: "スクールルック",
          pink: "ピンクコーデ",
          street: "ストリート",
          varsity: "バーシティジャケット",
          royal: "ロイヤル衣装",
          denim: "デニムセット",
          techwear: "テックウェア",
        },
        item: {
          lightstick: "ペンライト",
          mic: "マイク",
          photocard: "トレカ",
          crown: "王冠",
          camera: "チッケムカメラ",
          "heart-glasses": "ハート眼鏡",
          "star-bag": "星バッグ",
          "cat-ear": "猫耳",
        },
        aura: {
          sparkle: "スパークル",
          neon: "ネオン",
          heart: "ハート",
          star: "星明かり",
          spotlight: "スポットライト",
          purple: "パープルグロー",
        },
      },
      idolGroups: {
        v01d: { tags: ["公式登録", "5人組バンド", "自社アーティスト"], status: "登録済み" },
        bts: { tags: ["レジェンド", "パフォーマンス", "グローバル"] },
        seventeen: { tags: ["自主制作", "シンクロダンス", "バラエティ"] },
        "stray-kids": { tags: ["強いサウンド", "パフォーマンス", "グローバル"] },
        enhypen: { tags: ["物語", "パフォーマンス", "ファンダム"] },
        txt: { tags: ["爽やか", "コンセプト", "ストーリー"] },
        blackpink: { tags: ["アイコン", "ファッション", "グローバル"] },
        twice: { tags: ["ヒット曲", "ファンサ", "コンサート"] },
        aespa: { tags: ["世界観", "ボーカル", "コンセプト"] },
        ive: { tags: ["自己肯定感", "ビジュアル", "サビ"] },
        "le-sserafim": { tags: ["パフォーマンス", "堂々", "ステージ"] },
      },
      themes: {
        "neon-basement": { label: "ネオン地下室", vibe: "暗い照明と蛍光サイン" },
        "after-class": { label: "放課後の教室", vibe: "机の間でこっそり遊ぶ放課後" },
        "space-station": { label: "宇宙ステーション", vibe: "浮遊する会議室と冷たい照明" },
        "retro-gym": { label: "レトロ体育館", vibe: "ペンライトと拡声器のある体育祭" },
        "idol-backstage": { label: "アイドル楽屋", vibe: "控室、フォトウォール、本番前の緊張感" },
      },
      audiencePresets: {
        off: "観戦なし",
        small: "友だち20人",
        stream: "配信100人",
        fandom: "ファンダム300人",
      },
      notices: {
        "v01d-registered": {
          title: "V01D 登録完了",
          body: "男性5人組バンドグループ V01D が公式質問テーマとして登録されました。",
        },
        "kpop-pack-open": {
          title: "K-POPファンダム質問パック追加",
          body: "推し、カムバック、コンサート、トレカのテーマで遊べます。",
        },
      },
      heroSlides: {
        accuse: {
          tag: "2分ソーシャル推理",
          title: "答えひとつで友だちを疑おう。",
          body: "一人だけ違う質問を受けます。自然なふりをする答えを見抜いてください。",
        },
        v01d: {
          tag: "V01D質問テーマ",
          title: "推しバンドのテーマですぐ始めよう。",
          body: "V01Dを質問テーマに選んで、ファンダム同士で答えを疑ってみましょう。",
        },
      },
      characterPoses: {
        idle: "基本",
        point: "指差し",
        stage: "ステージ",
        think: "疑い",
      },
      packs: {
        kpop: {
          name: "K-POPファンダム",
          status: "ファン",
          tone: "推しの話だけで盛り上がれる質問",
          rounds: [
            {
              title: "カムバック",
              innocent: "カムバ初日にファンがまず確認するものは？",
              fake: "カムバ後しばらくしてから見てもいいものは？",
              answers: ["MV", "音源順位", "チッケム", "トレカ相場", "ビハインド", "スケジュール"],
              botAnswers: ["MV", "音源順位", "チッケム", "掛け声", "ショーケース"],
              fakeAnswers: ["ビハインド", "スケジュール", "字幕インタビュー", "グッズ在庫"],
            },
            {
              title: "推し",
              innocent: "推しにハマる入口として強いものは？",
              fake: "推し続けるために必要なものは？",
              answers: ["ステージ表情", "ライブ", "ファン愛", "バラエティ力", "交流", "実物レポ"],
              botAnswers: ["ステージ表情", "ライブ", "ファン愛", "バラエティ力"],
              fakeAnswers: ["交流", "実物レポ", "継続活動", "良いスタイリング"],
            },
            {
              title: "コンサート",
              innocent: "コンサート前に必ず持っていくものは？",
              fake: "コンサート後に整理すればいいものは？",
              answers: ["チケット", "ペンライト", "モバイルバッテリー", "スローガン", "感想", "グッズ整理"],
              botAnswers: ["チケット", "ペンライト", "モバイルバッテリー", "スローガン"],
              fakeAnswers: ["感想", "グッズ整理", "写真バックアップ", "セトリ復習"],
            },
            {
              title: "トレカ",
              innocent: "トレカ交換で一番大事なことは？",
              fake: "トレカ保管で一番大事なことは？",
              answers: ["傷確認", "相場", "認証写真", "手渡し場所", "スリーブ", "トップローダー"],
              botAnswers: ["傷確認", "相場", "認証写真", "手渡し場所"],
              fakeAnswers: ["スリーブ", "トップローダー", "湿気対策", "バインダー"],
            },
          ],
        },
        daily: {
          name: "日常",
          status: "基本",
          tone: "初めてでもすぐ答えられる質問",
          rounds: [
            {
              title: "コンビニ",
              innocent: "コンビニでよく買う夜食は？",
              fake: "コンビニであえて買わない食べ物は？",
              answers: ["おにぎり", "カップ麺", "ホットスナック", "ゼロコーラ", "水", "チョコ牛乳"],
              botAnswers: ["おにぎり", "カップ麺", "ホットスナック", "弁当", "トッポッキ"],
              fakeAnswers: ["水", "ガム", "サラダ", "ナッツ"],
            },
            {
              title: "デリバリー",
              innocent: "みんなで頼むのに良いデリバリーは？",
              fake: "一人で頼むのに良いデリバリーは？",
              answers: ["チキン", "ピザ", "麻辣湯", "トッポッキ", "寿司", "ハンバーガー"],
              botAnswers: ["チキン", "ピザ", "麻辣湯", "トッポッキ", "ポッサム"],
              fakeAnswers: ["ハンバーガー", "寿司", "サラダ", "丼"],
            },
            {
              title: "週末",
              innocent: "友だちと週末にやると楽しいことは？",
              fake: "一人の週末にやると楽しいことは？",
              answers: ["脱出ゲーム", "グルメ", "ボードゲーム", "カラオケ", "映画", "昼寝"],
              botAnswers: ["脱出ゲーム", "グルメ", "ボードゲーム", "カラオケ", "カフェ"],
              fakeAnswers: ["昼寝", "Netflix", "散歩", "ゲーム"],
            },
            {
              title: "グループチャット",
              innocent: "グループチャットで盛り上がる返し方は？",
              fake: "グループチャットで空気が冷える返し方は？",
              answers: ["短く面白く", "大きめリアクション", "画像を送る", "すぐ返信", "既読スルー", "正論パンチ"],
              botAnswers: ["短く面白く", "大きめリアクション", "画像を送る", "すぐ返信"],
              fakeAnswers: ["既読スルー", "正論パンチ", "長文アドバイス", "急に真面目"],
            },
          ],
        },
        romance: {
          name: "恋愛/気になる人",
          status: "人気",
          tone: "答えだけでいじれる質問",
          rounds: [
            {
              title: "初デート",
              innocent: "初デートに良い場所は？",
              fake: "一人時間に良い場所は？",
              answers: ["映画館", "カフェ", "川沿い", "展示会", "ネットカフェ", "家"],
              botAnswers: ["映画館", "カフェ", "川沿い", "展示会", "レストラン"],
              fakeAnswers: ["家", "ネットカフェ", "本屋", "散歩"],
            },
            {
              title: "返信",
              innocent: "好意がある時に送りやすい返信は？",
              fake: "興味が薄い時に送りがちな返信は？",
              answers: ["笑笑笑", "いつ会う？", "私も好き", "写真を送る", "うん", "忙しい"],
              botAnswers: ["笑笑笑", "いつ会う？", "私も好き", "写真を送る"],
              fakeAnswers: ["うん", "忙しい", "また今度", "既読で止める"],
            },
            {
              title: "プレゼント",
              innocent: "軽くもらって嬉しいプレゼントは？",
              fake: "もらうと少し重いプレゼントは？",
              answers: ["コーヒー券", "デザート", "香水", "花", "ペアグッズ", "手紙"],
              botAnswers: ["コーヒー券", "デザート", "花", "キーホルダー"],
              fakeAnswers: ["ペアグッズ", "高い香水", "手紙", "服"],
            },
          ],
        },
        party: {
          name: "合宿/飲み会",
          status: "パーティー",
          tone: "短く笑えるグループ向け質問",
          rounds: [
            {
              title: "旅行",
              innocent: "友だちと旅行に行ったら必ずすることは？",
              fake: "一人旅に行ったら必ずすることは？",
              answers: ["グルメ探し", "写真を撮る", "宿で休む", "夜市", "カフェ巡り", "寝坊"],
              botAnswers: ["グルメ探し", "写真を撮る", "夜市", "カフェ巡り", "お土産探し"],
              fakeAnswers: ["寝坊", "一人ご飯", "宿で休む", "読書"],
            },
            {
              title: "カラオケ",
              innocent: "カラオケの最初の曲に良いジャンルは？",
              fake: "カラオケの最後の曲に良いジャンルは？",
              answers: ["バラード", "ダンス曲", "アイドル曲", "ラップ", "OST", "みんなで歌う曲"],
              botAnswers: ["ダンス曲", "アイドル曲", "盛り上がる曲", "みんなで歌う曲", "知ってる曲"],
              fakeAnswers: ["バラード", "失恋ソング", "高音曲", "静かなOST"],
            },
            {
              title: "飲みゲーム",
              innocent: "初対面でもやりやすい飲みゲームは？",
              fake: "仲良い人同士じゃないと気まずい飲みゲームは？",
              answers: ["369", "タイミングゲーム", "いちごゲーム", "しりとり", "真実ゲーム", "イメージゲーム"],
              botAnswers: ["369", "タイミングゲーム", "いちごゲーム", "しりとり"],
              fakeAnswers: ["真実ゲーム", "イメージゲーム", "究極の選択", "王様ゲーム"],
            },
            {
              title: "宿",
              innocent: "合宿の宿で最初に決めることは？",
              fake: "合宿の宿で最後に決めてもいいことは？",
              answers: ["部屋割り", "買い出し", "夕飯", "お酒係", "朝ごはん", "掃除順"],
              botAnswers: ["部屋割り", "買い出し", "夕飯", "お酒係"],
              fakeAnswers: ["朝ごはん", "掃除順", "帰る時間", "写真整理"],
            },
          ],
        },
        campus: {
          name: "学校/サークル",
          status: "友だち",
          tone: "クラス、サークル、学科の集まりで使いやすい質問",
          rounds: [
            { title: "休み時間", innocent: "休み時間に友だちとやると良いことは？", fake: "授業直前にやると良いことは？", answers: ["売店", "おしゃべり", "トイレ", "リールを見る", "水を飲む", "席を整える"], botAnswers: ["売店", "おしゃべり", "トイレ", "リールを見る"], fakeAnswers: ["水を飲む", "席を整える", "教材を出す", "筆記具を探す"] },
            { title: "グループ課題", innocent: "グループ課題で最初に決めることは？", fake: "課題が終わってから整理してもいいことは？", answers: ["役割", "締切", "資料調査", "発表者", "感想", "ファイル名"], botAnswers: ["役割", "締切", "資料調査", "発表者"], fakeAnswers: ["感想", "ファイル名", "表紙デザイン", "打ち上げ"] },
            { title: "サークル", innocent: "新入部員に先に教えることは？", fake: "長くいる人だけ知っていればいいことは？", answers: ["活動時間", "グループチャット", "会費", "場所", "伝統", "打ち上げの店"], botAnswers: ["活動時間", "グループチャット", "会費", "場所"], fakeAnswers: ["伝統", "打ち上げの店", "昔の話", "運営のあだ名"] },
            { title: "試験期間", innocent: "試験前日に一番助かるものは？", fake: "試験後にやってもいいことは？", answers: ["要約", "過去問", "暗記", "睡眠", "採点", "打ち上げ"], botAnswers: ["要約", "過去問", "暗記", "睡眠"], fakeAnswers: ["採点", "打ち上げ", "本の整理", "次の計画"] },
          ],
        },
        work: {
          name: "会社/バイト",
          status: "共感",
          tone: "仕事、バイト、プロジェクトで出るリアルな質問",
          rounds: [
            { title: "会議", innocent: "会議前に準備すると良いものは？", fake: "会議後に整理してもいいものは？", answers: ["議題", "資料", "質問", "時間確認", "議事録", "昼ごはん"], botAnswers: ["議題", "資料", "質問", "時間確認"], fakeAnswers: ["議事録", "昼ごはん", "カレンダー整理", "雑談"] },
            { title: "バイト交代", innocent: "交代前に必ず確認することは？", fake: "退勤後に確認してもいいことは？", answers: ["在庫", "レジ", "引き継ぎ", "掃除状態", "給料日", "グループチャット"], botAnswers: ["在庫", "レジ", "引き継ぎ", "掃除状態"], fakeAnswers: ["給料日", "グループチャット", "レビュー", "制服洗濯"] },
            { title: "締切", innocent: "締切直前に一番危ないものは？", fake: "締切後にやってもいいものは？", answers: ["誤字", "抜け", "共有忘れ", "バグ", "振り返り", "フォルダ整理"], botAnswers: ["誤字", "抜け", "共有忘れ", "バグ"], fakeAnswers: ["振り返り", "フォルダ整理", "成果キャプチャ", "感想"] },
            { title: "メッセンジャー", innocent: "仕事チャットですぐ返すべきものは？", fake: "後で返してもいいものは？", answers: ["緊急依頼", "障害", "会議変更", "承認", "雑談", "絵文字"], botAnswers: ["緊急依頼", "障害", "会議変更", "承認"], fakeAnswers: ["雑談", "絵文字", "昼ごはん話", "リンク共有"] },
          ],
        },
        creator: {
          name: "配信/ストリーマー",
          status: "配信",
          tone: "配信者と視聴者が一緒に楽しめる質問",
          rounds: [
            { title: "チャット欄", innocent: "チャット欄を盛り上げる言葉は？", fake: "チャット欄を冷ます言葉は？", answers: ["笑笑笑", "伝説", "クリップ案件", "ナイス", "指示", "比較"], botAnswers: ["笑笑笑", "伝説", "クリップ案件", "ナイス"], fakeAnswers: ["指示", "比較", "ネタバレ", "急な重い質問"] },
            { title: "コラボ", innocent: "コラボで先に合わせることは？", fake: "コラボ後に見てもいいことは？", answers: ["時間", "ゲーム", "ルール", "音量", "クリップ", "感想"], botAnswers: ["時間", "ゲーム", "ルール", "音量"], fakeAnswers: ["クリップ", "感想", "サムネ", "コメント"] },
            { title: "投げ銭", innocent: "投げ銭で送ると反応が良いものは？", fake: "投げ銭で送ると負担になるものは？", answers: ["短いネタ", "応援", "お祝い", "リアクションお願い", "長文", "個人質問"], botAnswers: ["短いネタ", "応援", "お祝い", "リアクションお願い"], fakeAnswers: ["長文", "個人質問", "比較", "無理なお願い"] },
            { title: "ファン心", innocent: "ファンが長く残る理由は？", fake: "新規がすぐ見づらいものは？", answers: ["継続", "交流", "面白さ", "雰囲気", "内輪ネタ", "昔の事件"], botAnswers: ["継続", "交流", "面白さ", "雰囲気"], fakeAnswers: ["内輪ネタ", "昔の事件", "長い告知", "複雑なルール"] },
          ],
        },
        game: {
          name: "ゲーム/ランク",
          status: "ゲーム",
          tone: "ゲーマー同士ですぐ議論になる質問",
          rounds: [
            { title: "ランク", innocent: "ランクを上げる時に一番大事なものは？", fake: "ランクが落ちた時によくある言い訳は？", answers: ["メンタル", "フィジカル", "マップ理解", "連携", "味方運", "ラグ"], botAnswers: ["メンタル", "フィジカル", "マップ理解", "連携"], fakeAnswers: ["味方運", "ラグ", "マッチング", "コンディション"] },
            { title: "パーティーゲーム", innocent: "友だちとやると笑える要素は？", fake: "一人でやると楽な要素は？", answers: ["裏切り", "ランダム", "罰ゲーム", "ボイスチャット", "周回", "ストーリー"], botAnswers: ["裏切り", "ランダム", "罰ゲーム", "ボイスチャット"], fakeAnswers: ["周回", "ストーリー", "設定変更", "チュートリアル"] },
            { title: "装備", innocent: "ゲーム開始前に設定すべきものは？", fake: "ゲーム後に変えてもいいものは？", answers: ["感度", "キー設定", "音量", "グラフィック", "ニックネーム", "プロフィール"], botAnswers: ["感度", "キー設定", "音量", "グラフィック"], fakeAnswers: ["ニックネーム", "プロフィール", "スキン", "称号"] },
            { title: "ボイスチャット", innocent: "ゲーム中にすぐ声で言うべきことは？", fake: "ゲーム後に言ってもいいことは？", answers: ["位置", "危険", "作戦", "必殺技", "感想", "リプレイ"], botAnswers: ["位置", "危険", "作戦", "必殺技"], fakeAnswers: ["感想", "リプレイ", "ハイライト", "褒める"] },
          ],
        },
        "travel-food": {
          name: "旅行/グルメ",
          status: "癒し",
          tone: "旅行計画とグルメの好みで分かれる質問",
          rounds: [
            { title: "宿", innocent: "旅行の宿を選ぶ時に大事なものは？", fake: "宿に着いてから見てもいいものは？", answers: ["場所", "価格", "清潔さ", "口コミ", "照明", "アメニティ"], botAnswers: ["場所", "価格", "清潔さ", "口コミ"], fakeAnswers: ["照明", "アメニティ", "景色の写真", "内装"] },
            { title: "グルメ", innocent: "お店選びで信じやすいものは？", fake: "お店に行った後に残るものは？", answers: ["口コミ", "写真", "地元のおすすめ", "メニュー", "レシート", "ストーリー"], botAnswers: ["口コミ", "写真", "地元のおすすめ", "メニュー"], fakeAnswers: ["レシート", "ストーリー", "記念写真", "感想"] },
            { title: "写真", innocent: "旅行写真を撮る前に見るものは？", fake: "旅行写真を撮った後にすることは？", answers: ["構図", "光", "背景", "表情", "加工", "投稿"], botAnswers: ["構図", "光", "背景", "表情"], fakeAnswers: ["加工", "投稿", "アルバム整理", "タグ"] },
            { title: "動線", innocent: "旅行初日に入れやすい予定は？", fake: "旅行最終日に入れやすい予定は？", answers: ["近くの店", "宿周辺", "軽い散歩", "夜市", "お土産", "荷造り"], botAnswers: ["近くの店", "宿周辺", "軽い散歩", "夜市"], fakeAnswers: ["お土産", "荷造り", "空港近く", "チェックアウト"] },
          ],
        },
      },
    },
  },
};
